### ISSUE TITLE
Support Go 1.22

### ISSUE THREAD

**Issue by stefanb** [lima-vm/lima#2133]
### Description

Trying to build with Go 1.22 (scheduled for February, currently rc1) fails with error:
````
# gvisor.dev/gvisor/pkg/sync
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230715022000-fd277b20b8db/pkg/sync/gate_unsafe.go:114:3: undefined: goready
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230715022000-fd277b20b8db/pkg/sync/gate_unsafe.go:144:2: undefined: gopark
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230715022000-fd277b20b8db/pkg/sync/rwmutex_unsafe.go:76:3: undefined: semacquire
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230715022000-fd277b20b8db/pkg/sync/rwmutex_unsafe.go:102:4: undefined: semrelease
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230715022000-fd277b20b8db/pkg/sync/rwmutex_unsafe.go:152:3: undefined: semacquire
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230715022000-fd277b20b8db/pkg/sync/rwmutex_unsafe.go:179:3: undefined: semrelease
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230715022000-fd277b20b8db/pkg/sync/rwmutex_unsafe.go:207:3: undefined: semrelease
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230715022000-fd277b20b8db/pkg/sync/seqcount.go:87:6: undefined: canSpin
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230715022000-fd277b20b8db/pkg/sync/seqcount.go:89:4: undefined: doSpin
````

Found when testing https://github.com/Homebrew/homebrew-core/pull/157782

The fix is likely updating the `gvisor.dev/gvisor` module, similar as it was done in https://github.com/superfly/flyctl/pull/3161

**Comment by AkihiroSuda** [comment]
Depends on:
- https://github.com/containers/gvisor-tap-vsock/issues/310
