### PR TITLE
go.mod: gvisor.dev/gvisor v0.0.0-20231023213702-2691a8f9b1cf (Support Go 1.22)

### LINKED ISSUE #2133: Support Go 1.22
### Description

Trying to build with Go 1.22 (scheduled for February, currently rc1) fails with error:
````
# gvisor.dev/gvisor/pkg/sync
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230715022000-fd277b20b8db/pkg/sync/gate_unsafe.go:114:3: undefined: goready
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230715022000-fd277b20b8db/pkg/sync/gate_unsafe.go:144:2: undefined: gopark
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230715022000-fd277b20b8db/pkg/sync/rwmutex_unsafe.go:76:3: undefined: semacquire
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230715022000-fd277b20b8db/pkg/sync/rwmutex_unsafe.go:102:4: undefined: semrelease
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230715022000-fd277b20b8db/pkg/sync/rwmutex_unsafe.go:152:3: undefined: semacquire
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230715022000-fd277b20b8db/pkg/sync/rwmutex_unsafe.go:179:3: undefined: semrelease
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230715022000-fd277b20b8db/pkg/sync/rwmutex_unsafe.go:207:3: undefined: semrelease
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230715022000-fd277b20b8db/pkg/sync/seqcount.go:87:6: undefined: canSpin
/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230715022000-fd277b20b8db/pkg/sync/seqcount.go:89:4: undefined: doSpin
````

Found when testing https://github.com/Homebrew/homebrew-core/pull/157782

The fix is likely updating the `gvisor.dev/gvisor` module, similar as it was done in https://github.com/superfly/flyctl/pull/3161

### PR DESCRIPTION
**Pull request by AkihiroSuda**
This revision is compatible with Go 1.20, 1.21, and 1.22rc1. New versions (>= v0.0.0-20231024051821-3b00acd67af2) are no longer compatible with Go 1.20.

Fixes #2133

### CODE REVIEW

**Comment by jandubois** [comment]
> This revision is compatible with Go 1.20, 1.21, and 1.22rc1.

I know there is nothing we can do about this, but this narrow coupling between package versions and Go releases makes it quite painful to run `git bisect` over a range of Lima releases, as different commits will need to be compiled with different Go versions.

I hope at some point they will become compatible with all upcoming Go releases; the Go team spends a lot of effort on keeping Go backwards compatible...

**Comment by AkihiroSuda** [comment]
> > This revision is compatible with Go 1.20, 1.21, and 1.22rc1.
> 
> I know there is nothing we can do about this, but this narrow coupling between package versions and Go releases makes it quite painful to run `git bisect` over a range of Lima releases, as different commits will need to be compiled with different Go versions.
> 
> I hope at some point they will become compatible with all upcoming Go releases; the Go team spends a lot of effort on keeping Go backwards compatible...

Yes, maybe we can consider using another TCP/IP implementation if they aren't interested in supporting multiple Go versions

**Comment by AkihiroSuda** [comment]
Can we merge this?

**Review by jandubois — APPROVED** [review]
LGTM, thanks!
